mysql:
  driver: mysql
  source: root:tp,.39w?%k@tcp(localhost:3306)/rent?parseTime=true
server:
  port: 8080
  mode: debug
jwt:
  secret: sjdkljwaiknskdlnaknwkdnaksndsa
redis:
  addr: localhost:6379
  password: ""
  db: 0
email:
  host: smtp.qq.com
  port: 587
  username: 2824920336@qq.com
  password: mwdkosazcwwkdfce